# Generated by Django 2.2.1 on 2019-06-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='other_contact',
        ),
    ]
