# Generated by Django 2.2.1 on 2019-06-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_supplier_other_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='supplier',
            new_name='_supplier',
        ),
    ]
