# Generated by Django 2.2.1 on 2019-11-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190610_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('display_order', 'id')},
        ),
    ]
