# Generated by Django 2.2.1 on 2019-12-05 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productimage_display_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
    ]
