# Generated by Django 2.2.1 on 2019-12-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191205_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='main_picture',
            field=models.BooleanField(default=False),
        ),
    ]
