# Generated by Django 2.2.1 on 2019-12-31 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productimage_main_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.ImageField(upload_to='images/products'),
        ),
    ]
