# Generated by Django 2.2.9 on 2020-01-28 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_featuredproductimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredproductimage',
            old_name='Featured_product',
            new_name='featured_product',
        ),
    ]
