# Generated by Django 2.2.9 on 2020-01-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200127_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproduct',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
