# Generated by Django 2.2.9 on 2020-01-23 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20200117_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_receiver', models.CharField(max_length=100)),
                ('main_address', models.CharField(max_length=200)),
                ('secondary_address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=12)),
                ('phone_number', models.CharField(max_length=12)),
                ('updated_by', models.CharField(max_length=100)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('cart', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_details', to='cart.Cart')),
            ],
        ),
    ]
